spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-dev
    username: spring-dev
    password: password
    initialization-mode: always
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: database-create.sql
